package com.example.appprato.ui.theme

import androidx.compose.ui.graphics.Color

// Novos tons de verde
val Green_light_primary = Color(0xFF386A1F)
val Green_light_onPrimary = Color(0xFFFFFFFF)
val Green_light_primaryContainer = Color(0xFFB7F396)
val Green_light_onPrimaryContainer = Color(0xFF072100)
val Green_light_secondary = Color(0xFF56624B)
val Green_light_onSecondary = Color(0xFFFFFFFF)
val Green_light_secondaryContainer = Color(0xFFDAE7CA)
val Green_light_onSecondaryContainer = Color(0xFF141F0D)
val Green_light_tertiary = Color(0xFF386666)
val Green_light_onTertiary = Color(0xFFFFFFFF)
val Green_light_tertiaryContainer = Color(0xFFBBEBEB)
val Green_light_onTertiaryContainer = Color(0xFF002020)
val Green_light_error = Color(0xFFBA1A1A)
val Green_light_errorContainer = Color(0xFFFFDAD6)
val Green_light_onError = Color(0xFFFFFFFF)
val Green_light_onErrorContainer = Color(0xFF410002)
val Green_light_background = Color(0xFFFDFDF5)
val Green_light_onBackground = Color(0xFF1A1C18)
val Green_light_surface = Color(0xFFFDFDF5)
val Green_light_onSurface = Color(0xFF1A1C18)
val Green_light_surfaceVariant = Color(0xFFE0E4D6)
val Green_light_onSurfaceVariant = Color(0xFF43483E)
val Green_light_outline = Color(0xFF74796D)
val Green_light_inverseOnSurface = Color(0xFFF1F1EA)
val Green_light_inverseSurface = Color(0xFF2F312C)
val Green_light_inversePrimary = Color(0xFF9CD67D)
val Green_light_surfaceTint = Color(0xFF386A1F)

val Green_dark_primary = Color(0xFF9CD67D)
val Green_dark_onPrimary = Color(0xFF113800)
val Green_dark_primaryContainer = Color(0xFF205105)
val Green_dark_onPrimaryContainer = Color(0xFFB7F396)
val Green_dark_secondary = Color(0xFFBECBB0)
val Green_dark_onSecondary = Color(0xFF283420)
val Green_dark_secondaryContainer = Color(0xFF3E4A35)
val Green_dark_onSecondaryContainer = Color(0xFFDAE7CA)
val Green_dark_tertiary = Color(0xFFA0CFCF)
val Green_dark_onTertiary = Color(0xFF003737)
val Green_dark_tertiaryContainer = Color(0xFF1E4E4E)
val Green_dark_onTertiaryContainer = Color(0xFFBBEBEB)
val Green_dark_error = Color(0xFFFFB4AB)
val Green_dark_errorContainer = Color(0xFF93000A)
val Green_dark_onError = Color(0xFF690005)
val Green_dark_onErrorContainer = Color(0xFFFFDAD6)
val Green_dark_background = Color(0xFF1A1C18)
val Green_dark_onBackground = Color(0xFFE3E3DC)
val Green_dark_surface = Color(0xFF1A1C18)
val Green_dark_onSurface = Color(0xFFE3E3DC)
val Green_dark_surfaceVariant = Color(0xFF43483E)
val Green_dark_onSurfaceVariant = Color(0xFFC4C8BB)
val Green_dark_outline = Color(0xFF8E9286)
val Green_dark_inverseOnSurface = Color(0xFF1A1C18)
val Green_dark_inverseSurface = Color(0xFFE3E3DC)
val Green_dark_inversePrimary = Color(0xFF386A1F)
val Green_dark_surfaceTint = Color(0xFF9CD67D)
